### ISSUE TITLE
Add permalink on each title

### ISSUE THREAD

**Issue by TotomInc** [papercss/vuejs-papercss#10]
Since we have `vue-router` we can add permalinks on titles to reach them, like in Bootstrap docs for example.

![image](https://user-images.githubusercontent.com/9285210/33798673-32d914ba-dd1d-11e7-81d0-9c5f6afbfcef.png)

**Comment by CalebBassham** [comment]
I set the Download tutorial to have an id and I tried to link it with `<a href="#download">link</a>` but the `#` in the URL was breaking it. Is there a separate way to do it with vue-router?

**Comment by TotomInc** [comment]
I don't have a lot of experience with `vue-router` but I have the feeling that it is going to be way more complex than what we expect.

**Comment by CalebBassham** [comment]
I would say keep an eye out but this shouldn't be too big of a priority as long as it is easy to find what you are looking for.

**Comment by CalebBassham** [comment]
Not sure this is possible with the style of router we use, as it uses ids as the routes.
