### ISSUE TITLE
ESLint

### ISSUE THREAD

**Issue by CalebBassham** [papercss/vuejs-papercss#12]
I think that it would be a good to add ESLint to the project so that we can have a consistent code style thought the whole thing. I don't think that it would matter to be the same as the other projects but if they have a decent rule set already than that would be a good base.

**Comment by TotomInc** [comment]
I'll work on this one and add Airbnb JavaScript rules.

**Comment by CalebBassham** [comment]
Sounds good

**Comment by TotomInc** [comment]
This will be worked on before the 0.1.0 release, which will feature vue-papercss as an official vue-plugin.

**Comment by TotomInc** [comment]
Added with #51
