### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by CalebBassham** [papercss/vuejs-papercss#30]
Will the demo be deployed using GitHub pages? When do you plan the first deployment? When do you plan to add it to NPM? We are pretty close to having all of the components ported over and the documentation shouldn't take too long either.

**Comment by TotomInc** [comment]
They are using netlify on papercss docs, maybe we can use that too. @rhyneav can setup everything, we need to know if it's possible to do the same thing for vuejs-papercss.

**Comment by CalebBassham** [comment]
Netlify should work fine as long as it supports JS. We may want to move the demo into its own repository. It would be much easier to deploy and the demos have dependencies that vuejs-papercss doesn't so it is bloating for people who are just trying to get the components.
