### ISSUE TITLE
Update papercss link in package.json

### ISSUE THREAD

**Issue by TotomInc** [papercss/vuejs-papercss#31]
Once papercss reach 1.3.0 (I hope in the end of the week), we need to update the link in the `package.json`, which is pointing to the `separate-components` branch.

**Comment by CalebBassham** [comment]
I was just about to mention this for stability.

**Comment by rhyneav** [comment]
1.3.0 is live! https://github.com/papercss/papercss/releases/tag/v1.3.0

And while I know this isn't the spot for this, I wanted to say that the updated README for PaperCSS is absolutely stellar. Thank you for the awesome work @TotomInc!
