### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by CalebBassham** [papercss/vuejs-papercss#4]
Are we going to include documentation like installation and some simple examples of using it with Vue in the demo?

Also, are you in the slack @TotomInc

**Comment by TotomInc** [comment]
I'm not actually on the slack server of papercss. I'll try to join it when I have some time.

Actually, I wanted to focus on the features first before writing anything related to documentation. But if you are interested about the making of this, you can do it.

**Comment by CalebBassham** [comment]
@TotomInc Alright, I am interested in doing some of the documentation but I can help out with some of the features, it looks like there is a pretty good collection of them so far so I will create some documentation for those and then work on components.

I have never worked on a library like this so I was wonder what the purpose is for having a separate `index.js` for every component.

**Comment by TotomInc** [comment]
Getting an `index.js` for each component allow for easy refactoring and a better tree structure.
